export const CHAT_LIST = [
  {
    _id: "anna_ivanova",
    fullName: "Анна Иванова",
    username: "anna_ivanova",
    email: "anna@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "petr_petrov",
    fullName: "Петр Петров",
    username: "petr_petrov",
    email: "petr@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "maria_sidorova",
    fullName: "Мария Сидорова",
    username: "maria_sidorova",
    email: "maria@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "ivan_kozlov",
    fullName: "Иван Козлов",
    username: "ivan_kozlov",
    email: "ivan@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "elena_smirnova",
    fullName: "Елена Смирнова",
    username: "elena_smirnova",
    email: "elena@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "dmitry_volkov",
    fullName: "Дмитрий Волков",
    username: "dmitry_volkov",
    email: "dmitry@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "olga_novikova",
    fullName: "Ольга Новикова",
    username: "olga_novikova",
    email: "olga@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "sergey_morozov",
    fullName: "Сергей Морозов",
    username: "sergey_morozov",
    email: "sergey@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "tatyana_lebedeva",
    fullName: "Татьяна Лебедева",
    username: "tatyana_lebedeva",
    email: "tatyana@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "alexey_sokolov",
    fullName: "Алексей Соколов",
    username: "alexey_sokolov",
    email: "alexey@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "natalya_popova",
    fullName: "Наталья Попова",
    username: "natalya_popova",
    email: "natalya@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "mikhail_fedorov",
    fullName: "Михаил Федоров",
    username: "mikhail_fedorov",
    email: "mikhail@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "ekaterina_medvedeva",
    fullName: "Екатерина Медведева",
    username: "ekaterina_medvedeva",
    email: "ekaterina@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "andrey_pavlov",
    fullName: "Андрей Павлов",
    username: "andrey_pavlov",
    email: "andrey@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "yulia_orlova",
    fullName: "Юлия Орлова",
    username: "yulia_orlova",
    email: "yulia@example.com",
    profilePic: "/avatar.svg",
  },
  {
    _id: "roman_kuznetsov",
    fullName: "Роман Кузнецов",
    username: "roman_kuznetsov",
    email: "roman@example.com",
    profilePic: "/avatar.svg",
  },
];

